/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokemonExplorerRouteImport } from './routes/pokemon-explorer'
import { Route as PokemonDetailsPokemonNameRouteImport } from './routes/pokemon-details/$pokemonName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonExplorerRoute = PokemonExplorerRouteImport.update({
  id: '/pokemon-explorer',
  path: '/pokemon-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonDetailsPokemonNameRoute =
  PokemonDetailsPokemonNameRouteImport.update({
    id: '/pokemon-details/$pokemonName',
    path: '/pokemon-details/$pokemonName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemon-explorer': typeof PokemonExplorerRoute
  '/pokemon-details/$pokemonName': typeof PokemonDetailsPokemonNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemon-explorer': typeof PokemonExplorerRoute
  '/pokemon-details/$pokemonName': typeof PokemonDetailsPokemonNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pokemon-explorer': typeof PokemonExplorerRoute
  '/pokemon-details/$pokemonName': typeof PokemonDetailsPokemonNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokemon-explorer' | '/pokemon-details/$pokemonName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokemon-explorer' | '/pokemon-details/$pokemonName'
  id: '__root__' | '/' | '/pokemon-explorer' | '/pokemon-details/$pokemonName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokemonExplorerRoute: typeof PokemonExplorerRoute
  PokemonDetailsPokemonNameRoute: typeof PokemonDetailsPokemonNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon-explorer': {
      id: '/pokemon-explorer'
      path: '/pokemon-explorer'
      fullPath: '/pokemon-explorer'
      preLoaderRoute: typeof PokemonExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon-details/$pokemonName': {
      id: '/pokemon-details/$pokemonName'
      path: '/pokemon-details/$pokemonName'
      fullPath: '/pokemon-details/$pokemonName'
      preLoaderRoute: typeof PokemonDetailsPokemonNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokemonExplorerRoute: PokemonExplorerRoute,
  PokemonDetailsPokemonNameRoute: PokemonDetailsPokemonNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
